anchor_version = "0.22.0"

[features]
seeds = false

[programs.localnet]
cyclos_core = "cysPXAjehMpVKUapzbMCCnpFxUFFryEWEaLgnb9NrR8"

[programs.devnet]
cyclos_core = "cysPXAjehMpVKUapzbMCCnpFxUFFryEWEaLgnb9NrR8"

[programs.mainnet]
cyclos_core = "cysPXAjehMpVKUapzbMCCnpFxUFFryEWEaLgnb9NrR8"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 10000000 tests/**/*.ts"

[test]
startup_wait = 20000

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./external-programs/spl_token_metadata.so"

[[test.genesis]]
address = "GokivDYuQXPZCWRkwMhdH2h91KpDQXBEmpgBgs55bnpH"
program = "./external-programs/smart_wallet.so"

[[test.genesis]]
address = "Govz1VyoyLD5BL6CSCxUJLVLsQHRwjfFj1prNsdNg5Jw"
program = "./external-programs/govern.so"

[[test.genesis]]
address = "LocktDzaV1W2Bm9DeZeiyz4J9zs4fRqNiYqQyracRXw"
program = "./external-programs/locked_voter.so"