[programs.localnet]
cyclos_core = "37kn8WUzihQoAnhYxueA2BnqCA7VRnrVvYoHy1hQ6Veu"
swap_router = "A16PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 10000000 tests/**/*.ts"

[test]
startup_wait = 20000

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./spl_token_metadata/spl_token_metadata.so"
